# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# The `.rspec` file also contains a few flags that are not defaults but that
# users commonly want.
#

#ENV["RAILS_ENV"] ||= 'test'
#require File.expand_path("../../config/environment", FILE)

RSpec.configure do |config|

  #config.use_transactional_fixtures = false
  config.mock_with :rspec
  #config.order = "random"
  config.before(:each) do
    #Mongoid.purge!
    sign_out :user
  end

end